source 'https://rubygems.org'

ruby '2.6.1'

# ======== #
# Database #
# ======== #
gem 'pg'
gem 'github-ldap'
gem 'ladle', require: true

# ======= #
# General #
# ======= #
gem 'irb'
gem 'irbtools'
gem 'awesome_print'
gem 'logging'

# ======= #
# Testing #
# ======= #
gem 'rspec'
gem 'pry'


# fp = DBFileParse.new
# fp.read_db_config
