---

triggers:
  - name: tmp_id_table
    function:
      return: trigger
      sql: |
        create table if not exists insert_ids (ins_id integer, ins_table varchar(20));
        insert into insert_ids (ins_id, ins_table) values (new.id, TG_TABLE_NAME);
        return(new);
    trigger:
      event: after insert on <TRIGGERTABLE>
      execute: for each row execute procedure

...
# has to be a better way of keeping db clean of temp tables.
